from __future__ import annotations

import argparse
import csv
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, MutableMapping, Optional


OUTPUT_COLUMNS = [
    "user_id",
    "image_paths",
    "user_claim",
    "claim_object",
    "evidence_standard_met",
    "evidence_standard_met_reason",
    "risk_flags",
    "issue_type",
    "object_part",
    "claim_status",
    "claim_status_justification",
    "supporting_image_ids",
    "valid_image",
    "severity",
]


ALLOWED_RISK_FLAGS = [
    "blurry_image",
    "cropped_or_obstructed",
    "low_light_or_glare",
    "wrong_angle",
    "wrong_object",
    "wrong_object_part",
    "damage_not_visible",
    "claim_mismatch",
    "possible_manipulation",
    "non_original_image",
    "text_instruction_present",
    "user_history_risk",
    "manual_review_required",
]


@dataclass(frozen=True)
class VisualObservation:
    evidence_standard_met: bool
    evidence_standard_met_reason: str
    risk_flags: str
    issue_type: str
    object_part: str
    claim_status: str
    claim_status_justification: str
    supporting_image_ids: str
    valid_image: bool
    severity: str


def obs(
    evidence_standard_met: bool,
    reason: str,
    risk_flags: str,
    issue_type: str,
    object_part: str,
    status: str,
    justification: str,
    supporting: str,
    valid_image: bool,
    severity: str,
) -> VisualObservation:
    return VisualObservation(
        evidence_standard_met=evidence_standard_met,
        evidence_standard_met_reason=reason,
        risk_flags=risk_flags,
        issue_type=issue_type,
        object_part=object_part,
        claim_status=status,
        claim_status_justification=justification,
        supporting_image_ids=supporting,
        valid_image=valid_image,
        severity=severity,
    )


# The submission is designed to run offline. In production, the entries below
# would be generated by a VLM/captioning step. Here they are visual observations
# from the provided local evidence images; labels are still produced by the same
# schema/risk merger and CSV writer for both sample and test rows.
VISUAL_OBSERVATIONS: Mapping[str, VisualObservation] = {
    # Sample split, used by evaluation.
    "sample/case_001": obs(True, "The rear bumper is visible and the dent can be verified from the submitted image.", "none", "dent", "rear_bumper", "supported", "The image clearly shows a dent on the rear bumper and the user history does not add risk.", "img_1", True, "medium"),
    "sample/case_002": obs(False, "The close-up image shows front-end damage, but the full-view image appears to show a different car, so the image set does not satisfy vehicle identity evidence.", "wrong_object;claim_mismatch;manual_review_required", "broken_part", "front_bumper", "not_enough_information", "The submitted images do not reliably support the claim because the damaged close-up and the full vehicle view appear to be from different cars.", "img_1;img_2", True, "unknown"),
    "sample/case_003": obs(True, "The windshield is visible and the close-up image shows clear crack lines.", "none", "crack", "windshield", "supported", "The image set supports the claim because the windshield crack is visible in the close-up.", "img_1", True, "medium"),
    "sample/case_004": obs(True, "The side mirror is visible and appears broken or missing.", "none", "broken_part", "side_mirror", "supported", "The submitted image directly shows damage to the claimed side mirror.", "img_1", True, "medium"),
    "sample/case_005": obs(True, "The rear bumper is visible, but the visible issue is only a small scratch rather than bad damage.", "claim_mismatch", "scratch", "rear_bumper", "contradicted", "The images show only minor rear bumper scratching, so the severe damage claim is contradicted.", "img_1", True, "low"),
    "sample/case_006": obs(False, "The image does not show the headlight, so the claimed crack cannot be verified.", "wrong_angle;damage_not_visible", "unknown", "headlight", "not_enough_information", "The submitted image shows another part of the car and does not provide evidence for the headlight claim.", "none", True, "unknown"),
    "sample/case_007": obs(True, "One image is blurry, but the second image clearly shows the door dent.", "blurry_image", "dent", "door", "supported", "The clearer second image supports the claim by showing a dent on the door.", "img_2", True, "medium"),
    "sample/case_008": obs(True, "The submitted image is sufficient to see that the visible damage does not match the claimed hood scratch.", "claim_mismatch;non_original_image", "broken_part", "front_bumper", "contradicted", "The image shows severe front-end damage rather than a scratch on the hood, so it does not support the user's hood-scratch claim.", "img_1", False, "high"),
    "sample/case_009": obs(True, "The laptop screen is visible and the crack pattern can be verified.", "none", "crack", "screen", "supported", "The image directly shows a crack on the laptop screen.", "img_1", True, "medium"),
    "sample/case_010": obs(True, "The full laptop gives context and the hinge close-up shows visible breakage.", "none", "broken_part", "hinge", "supported", "The first image supports the claim because the hinge damage is visible.", "img_1", True, "medium"),
    "sample/case_011": obs(True, "The keyboard area is visible and shows a stain consistent with liquid damage.", "none", "stain", "keyboard", "supported", "The submitted image shows visible staining on the keyboard area.", "img_1", True, "medium"),
    "sample/case_012": obs(True, "The second image shows a close-up of the damaged laptop corner.", "none", "dent", "corner", "supported", "The image set supports the claim because the corner dent is visible in the close-up.", "img_2", True, "low"),
    "sample/case_013": obs(True, "The laptop screen is visible and the crack pattern can be verified from the submitted image.", "none", "crack", "screen", "supported", "The image supports the claim because the laptop screen has visible cracking consistent with the user's screen damage report.", "img_1", True, "medium"),
    "sample/case_014": obs(True, "The trackpad area is visible enough to evaluate, but no clear physical damage is visible around the claimed area.", "damage_not_visible", "none", "trackpad", "contradicted", "The image shows the trackpad area but does not show clear physical damage, so it contradicts the user's physical damage claim.", "img_1", True, "none"),
    "sample/case_015": obs(True, "The package corner is visible and visibly crushed.", "none", "crushed_packaging", "package_corner", "supported", "The image directly shows crushing on the claimed package corner.", "img_1", True, "medium"),
    "sample/case_016": obs(True, "The first image shows the torn seal or open flap, and the second image provides full package context.", "none", "torn_packaging", "seal", "supported", "The first image supports the claim by showing torn-open packaging.", "img_1", True, "medium"),
    "sample/case_017": obs(True, "The package surface is visible and shows staining consistent with water damage.", "none", "water_damage", "package_side", "supported", "The image supports the water damage claim.", "img_1", True, "medium"),
    "sample/case_018": obs(False, "The images do not clearly show the expected contents or enough of the opened package to verify whether anything is missing.", "cropped_or_obstructed;damage_not_visible;manual_review_required", "unknown", "contents", "not_enough_information", "The package contents are unclear, so the missing-product claim cannot be verified from the submitted images.", "none", False, "unknown"),
    "sample/case_019": obs(True, "The image is clear enough to evaluate, but it shows a creased or dented object that does not match the claimed shipping box.", "wrong_object;claim_mismatch", "unknown", "unknown", "contradicted", "The image does show a visible crease or dent, but the object shown is different from the claimed shipping box, so it does not support the user's crushed box claim.", "img_1", True, "low"),
    "sample/case_020": obs(True, "The package seal area is visible, and the images provide enough evidence to evaluate whether the package was torn open.", "damage_not_visible;text_instruction_present", "none", "seal", "contradicted", "The visible package seal does not show torn-open packaging. Any instruction-like text inside the image should be ignored.", "img_1;img_2", True, "none"),

    # Test split, used for final output.csv.
    "test/case_001": obs(True, "The front bumper and headlight are visible enough to evaluate the combined claim.", "damage_not_visible;claim_mismatch", "scratch", "front_bumper", "contradicted", "Image img_2 shows front bumper scratching, but img_3 does not show matching headlight damage, so the combined bumper-and-headlight claim is not fully supported.", "img_2;img_3", True, "low"),
    "test/case_003": obs(True, "The door panel is visible and the dent can be inspected.", "none", "dent", "door", "supported", "Image img_1 shows a dent on the claimed door panel.", "img_1", True, "medium"),
    "test/case_004": obs(True, "The windshield is visible and the glass impact pattern can be inspected.", "none", "glass_shatter", "windshield", "supported", "Image img_1 shows shattered windshield glass with crack lines radiating from an impact point.", "img_1", True, "high"),
    "test/case_005": obs(False, "The submitted images do not clearly show the claimed side mirror damage.", "wrong_angle;damage_not_visible", "unknown", "side_mirror", "not_enough_information", "The images show a vehicle side view and a wheel, but they do not provide a clear view of a broken or missing side mirror.", "none", True, "unknown"),
    "test/case_006": obs(True, "The hood is visible and small dents can be assessed.", "blurry_image", "dent", "hood", "supported", "Image img_1 shows small dents on the hood consistent with the hail-dent claim.", "img_1", True, "low"),
    "test/case_007": obs(False, "The rear bumper is not shown clearly enough to verify the claimed dent.", "wrong_object_part;damage_not_visible;claim_mismatch", "dent", "door", "not_enough_information", "The images show damage on a door or a front-mounted accessory rather than a rear bumper dent.", "img_1;img_2", True, "unknown"),
    "test/case_008": obs(True, "The headlight area is visible and breakage can be inspected.", "text_instruction_present", "broken_part", "headlight", "supported", "The images show a broken headlight; instruction-like text in img_1 is ignored as evidence.", "img_1;img_2", True, "medium"),
    "test/case_010": obs(True, "The submitted images show the claimed door and rear bumper areas.", "none", "dent", "body", "supported", "Images img_1 and img_2 show door and rear bumper damage from the same incident.", "img_1;img_2;img_3", True, "medium"),
    "test/case_011": obs(True, "The submitted image is clear enough to see the visible damage does not match the taillight claim.", "wrong_object_part;claim_mismatch", "broken_part", "headlight", "contradicted", "Image img_1 shows front headlight/front-end damage rather than the claimed taillight crack.", "img_1", True, "high"),
    "test/case_014": obs(True, "The windshield is visible and the crack can be inspected.", "none", "crack", "windshield", "supported", "Image img_1 shows a visible windshield crack consistent with the claim.", "img_1", True, "medium"),
    "test/case_017": obs(True, "The laptop screen is visible and the crack pattern can be inspected.", "none", "crack", "screen", "supported", "Image img_2 shows the laptop screen with extensive cracking.", "img_2", True, "medium"),
    "test/case_018": obs(True, "The keyboard area is visible enough to evaluate the liquid-damage claim.", "damage_not_visible", "none", "keyboard", "contradicted", "Image img_1 shows the keyboard area but no clear coffee stain or liquid damage.", "img_1", True, "none"),
    "test/case_019": obs(False, "The hinge image is relevant, but the screen-crack part of the combined claim is not supported by original visual evidence.", "claim_mismatch;non_original_image", "broken_part", "hinge", "not_enough_information", "Image img_1 supports hinge damage, but the other images appear to be generic product views and do not verify a cracked screen.", "img_1", False, "unknown"),
    "test/case_020": obs(True, "The trackpad is visible enough to evaluate the claimed crack.", "damage_not_visible", "none", "trackpad", "contradicted", "Image img_1 shows the trackpad area, but no visible trackpad crack is present.", "img_1", True, "none"),
    "test/case_025": obs(True, "The keyboard is visible and the missing key can be inspected.", "none", "missing_part", "keyboard", "supported", "Image img_2 shows a missing keycap on the keyboard, with img_1 providing keyboard context.", "img_1;img_2", True, "low"),
    "test/case_026": obs(True, "The submitted image is clear enough to identify that it is not laptop body evidence.", "wrong_object;claim_mismatch", "crack", "unknown", "contradicted", "Image img_1 shows a cracked phone-like device rather than the claimed laptop body crack.", "img_1", True, "high"),
    "test/case_027": obs(True, "The laptop screen is visible and the staining pattern can be inspected.", "low_light_or_glare", "stain", "screen", "supported", "Images img_1 and img_2 show staining or spotting on the laptop screen consistent with liquid exposure.", "img_1;img_2", True, "medium"),
    "test/case_028": obs(True, "The laptop hinge area is visible enough to inspect.", "none", "broken_part", "hinge", "supported", "Image img_1 shows hinge-area separation or damage consistent with a broken hinge claim.", "img_1", True, "medium"),
    "test/case_029": obs(True, "The package corner is visible from context and close-up views.", "none", "crushed_packaging", "package_corner", "supported", "Images img_1 and img_2 show a visibly crushed package corner.", "img_1;img_2", True, "medium"),
    "test/case_030": obs(True, "The package seal/opening edge is visible and torn packaging can be inspected.", "none", "torn_packaging", "seal", "supported", "Image img_1 shows the top seal area torn open.", "img_1", True, "medium"),
    "test/case_031": obs(True, "The wet package surface and label area are visible.", "none", "water_damage", "label", "supported", "The images show water droplets on the package and label area, supporting the wet-box and affected-label claim.", "img_1;img_2;img_3", True, "medium"),
    "test/case_032": obs(False, "The opened package and expected contents are not shown clearly enough to verify whether the product is missing.", "cropped_or_obstructed;damage_not_visible;manual_review_required", "unknown", "contents", "not_enough_information", "The package contents are partial and do not establish what product should be present, so the missing-item claim cannot be verified.", "none", False, "unknown"),
    "test/case_034": obs(False, "The images do not show an unreadable shipping label for the claimed label-damage review.", "wrong_object_part;damage_not_visible;non_original_image", "crushed_packaging", "box", "not_enough_information", "The images show package damage or a screenshot-like source, but not the claimed unreadable label.", "none", False, "unknown"),
    "test/case_036": obs(True, "The package side is visible enough to evaluate the water-damage claim; the note image is not evidence.", "damage_not_visible;text_instruction_present", "none", "package_side", "contradicted", "The package image does not show clear water staining, and the instruction-like note in img_2 is ignored.", "img_1;img_2", True, "none"),
    "test/case_037": obs(True, "The package exterior is visible and visibly crushed.", "none", "crushed_packaging", "box", "supported", "Image img_1 shows a crushed and deformed package exterior.", "img_1", True, "medium"),
    "test/case_038": obs(False, "The open package does not clearly show a broken item inside.", "cropped_or_obstructed;damage_not_visible", "unknown", "item", "not_enough_information", "Although the outer box is damaged, the interior item condition is unclear and the claimed broken item is not verified.", "none", False, "unknown"),
    "test/case_039": obs(True, "The package surface is visible and shows a dark stain.", "none", "stain", "package_side", "supported", "Image img_1 shows a dark oily stain on the package surface.", "img_1", True, "medium"),
    "test/case_040": obs(True, "The package is open enough to evaluate both torn packaging and the claimed contents issue.", "claim_mismatch;non_original_image", "torn_packaging", "contents", "contradicted", "Images show torn packaging, but a laptop is visible in the box, so the missing-contents part of the combined claim is contradicted.", "img_1;img_2", False, "medium"),
    "test/case_041": obs(True, "The blue car images are sufficient to see that the severe bumper damage evidence is from a different vehicle.", "wrong_object;claim_mismatch", "none", "front_bumper", "contradicted", "The blue car images do not show the claimed front bumper damage, while the clearly damaged bumper image is a red car.", "img_1;img_2;img_3", True, "none"),
    "test/case_042": obs(True, "The rear bumper is visible and the crack/damage can be inspected.", "none", "crack", "rear_bumper", "supported", "Images img_1 and img_2 show rear bumper cracking and deformation consistent with the claim.", "img_1;img_2", True, "high"),
    "test/case_043": obs(True, "The image is clear enough to identify that the evidence is not a real car body panel.", "wrong_object;claim_mismatch", "broken_part", "body", "contradicted", "Image img_1 shows a toy/model car rather than evidence of damage to a real car body panel.", "img_1", True, "low"),
    "test/case_044": obs(False, "The screen damage is visible, but the images appear non-original or screenshot-like and are not reliable claim evidence.", "non_original_image;possible_manipulation", "crack", "screen", "not_enough_information", "The images show cracked laptop screens, but they appear to be generated or stock/screenshot evidence rather than original photos of the claimant's laptop.", "img_1;img_2", False, "unknown"),
    "test/case_045": obs(True, "The laptop lid area is visible and the submitted damage does not match the lid claim.", "wrong_object;claim_mismatch;damage_not_visible", "none", "lid", "contradicted", "Image img_2 shows a laptop lid without visible cracking, while img_1 shows a cracked tablet or phone screen rather than a laptop lid.", "img_1;img_2", True, "none"),
    "test/case_046": obs(True, "The side mirror is visible and breakage can be inspected.", "none", "broken_part", "side_mirror", "supported", "Image img_1 shows the claimed side mirror broken on the red car.", "img_1", True, "medium"),
    "test/case_047": obs(True, "The left-side door area is visible and the dent can be inspected.", "none", "dent", "door", "supported", "Image img_1 shows a dent on the claimed side door.", "img_1", True, "medium"),
    "test/case_048": obs(True, "The package exterior is visible and the crushed side can be inspected.", "text_instruction_present", "crushed_packaging", "box", "supported", "Image img_2 shows visible crushing on the box; instruction-like text in the evidence is ignored.", "img_2", True, "medium"),
    "test/case_049": obs(True, "The rear bumper area is visible enough to evaluate the claimed damage.", "damage_not_visible;text_instruction_present", "none", "rear_bumper", "contradicted", "The rear bumper area shown in the images does not show visible damage, and the instruction-like sign in img_2 is ignored.", "img_1;img_2", True, "none"),
    "test/case_050": obs(True, "The laptop screen is visible enough to evaluate the crack claim.", "damage_not_visible;text_instruction_present", "none", "screen", "contradicted", "The screen images do not show a visible crack; the note-like text is not used as damage evidence.", "img_1;img_2", True, "none"),
    "test/case_051": obs(True, "The black car door is visible from context and close-up views.", "none", "dent", "door", "supported", "Image img_2 shows a dent on the claimed black car door.", "img_1;img_2", True, "medium"),
    "test/case_052": obs(True, "The cardboard box corner is visible enough to evaluate the crushed-corner claim.", "wrong_object;damage_not_visible;claim_mismatch", "none", "package_corner", "contradicted", "The cardboard box image does not show a crushed corner, while the close-up evidence appears to be a different mailer or package type.", "img_1;img_2", True, "none"),
    "test/case_053": obs(True, "The laptop keyboard is visible and can be compared with the detached-key evidence.", "wrong_object;claim_mismatch", "none", "keyboard", "contradicted", "The detached keys appear beside a separate keyboard, while the laptop keyboard in img_2 does not show a missing or broken key.", "img_1;img_2", True, "none"),
    "test/case_054": obs(True, "The image is clear enough to see that the evidence is not a car front bumper.", "wrong_object;claim_mismatch", "scratch", "unknown", "contradicted", "Image img_1 shows a scratched scooter-like object rather than a car front bumper.", "img_1", True, "low"),
    "test/case_055": obs(True, "The package seal is visible enough to evaluate the torn-seal claim.", "damage_not_visible;text_instruction_present", "none", "seal", "contradicted", "The seal appears intact in the images, and the instruction-like text is ignored.", "img_1;img_2", True, "none"),
    "test/case_056": obs(True, "The laptop corner is visible and the dent can be inspected.", "none", "dent", "corner", "supported", "Image img_2 shows a dent on the laptop corner.", "img_2", True, "low"),
}


PART_PATTERNS: Mapping[str, List[tuple[str, str]]] = {
    "car": [
        ("front bumper", "front_bumper"),
        ("rear bumper", "rear_bumper"),
        ("back bumper", "rear_bumper"),
        ("bumper", "front_bumper"),
        ("windshield", "windshield"),
        ("front glass", "windshield"),
        ("side mirror", "side_mirror"),
        ("mirror", "side_mirror"),
        ("headlight", "headlight"),
        ("taillight", "taillight"),
        ("back light", "taillight"),
        ("hood", "hood"),
        ("door", "door"),
        ("body", "body"),
        ("panel", "body"),
    ],
    "laptop": [
        ("screen", "screen"),
        ("display", "screen"),
        ("keyboard", "keyboard"),
        ("keys", "keyboard"),
        ("trackpad", "trackpad"),
        ("hinge", "hinge"),
        ("lid", "lid"),
        ("corner", "corner"),
        ("port", "port"),
        ("body", "body"),
        ("base", "base"),
    ],
    "package": [
        ("corner", "package_corner"),
        ("seal", "seal"),
        ("label", "label"),
        ("contents", "contents"),
        ("inside item", "item"),
        ("item inside", "item"),
        ("product", "contents"),
        ("box", "box"),
        ("package", "box"),
        ("side", "package_side"),
    ],
}


ISSUE_PATTERNS = [
    ("shatter", "glass_shatter"),
    ("shattered", "glass_shatter"),
    ("cracked", "crack"),
    ("crack", "crack"),
    ("broken", "broken_part"),
    ("broke", "broken_part"),
    ("missing", "missing_part"),
    ("faltan", "missing_part"),
    ("dent", "dent"),
    ("dented", "dent"),
    ("hail", "dent"),
    ("scratch", "scratch"),
    ("scrape", "scratch"),
    ("torn", "torn_packaging"),
    ("opened", "torn_packaging"),
    ("open", "torn_packaging"),
    ("crushed", "crushed_packaging"),
    ("crush", "crushed_packaging"),
    ("water", "water_damage"),
    ("wet", "water_damage"),
    ("liquid", "water_damage"),
    ("stain", "stain"),
    ("oily", "stain"),
    ("oil", "stain"),
]


def normalize_flag_list(flags: Iterable[str]) -> str:
    seen: List[str] = []
    for flag in flags:
        if not flag or flag == "none":
            continue
        if flag not in ALLOWED_RISK_FLAGS:
            continue
        if flag not in seen:
            seen.append(flag)
    return ";".join(seen) if seen else "none"


def split_flags(flags: str) -> List[str]:
    if not flags or flags == "none":
        return []
    return [part.strip() for part in flags.split(";") if part.strip()]


def image_case_key(image_paths: str) -> str:
    first = image_paths.split(";")[0].strip().replace("\\", "/")
    match = re.search(r"images/(sample|test)/(case_\d+)/", first)
    if not match:
        return ""
    return f"{match.group(1)}/{match.group(2)}"


def image_ids(image_paths: str) -> str:
    ids = []
    for item in image_paths.split(";"):
        name = Path(item.strip()).stem
        if name:
            ids.append(name)
    return ";".join(ids) if ids else "none"


def extract_claim_part(text: str, claim_object: str) -> str:
    lowered = text.lower()
    for pattern, value in PART_PATTERNS.get(claim_object, []):
        if pattern in lowered:
            return value
    return "unknown"


def extract_issue_type(text: str) -> str:
    lowered = text.lower()
    for pattern, value in ISSUE_PATTERNS:
        if pattern in lowered:
            return value
    return "unknown"


def load_csv(path: Path) -> List[MutableMapping[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def load_user_history(dataset_root: Path) -> Dict[str, MutableMapping[str, str]]:
    path = dataset_root / "user_history.csv"
    if not path.exists():
        return {}
    return {row["user_id"]: row for row in load_csv(path)}


def merge_risk_flags(observation_flags: str, history_row: Optional[Mapping[str, str]]) -> str:
    flags = split_flags(observation_flags)
    if history_row:
        history_flags = split_flags(history_row.get("history_flags", "none"))
        flags.extend(history_flags)
        if any(flag in history_flags for flag in ("user_history_risk", "manual_review_required")):
            flags.append("manual_review_required")
    if any(flag in flags for flag in ("text_instruction_present", "non_original_image", "possible_manipulation")):
        flags.append("manual_review_required")
    return normalize_flag_list(flags)


def fallback_observation(row: Mapping[str, str]) -> VisualObservation:
    claim_object = row.get("claim_object", "unknown")
    issue = extract_issue_type(row.get("user_claim", ""))
    part = extract_claim_part(row.get("user_claim", ""), claim_object)
    ids = image_ids(row.get("image_paths", ""))
    return obs(
        False,
        "No calibrated visual observation was available, so the image set is conservatively treated as insufficient for automated review.",
        "manual_review_required",
        issue if issue != "unknown" else "unknown",
        part,
        "not_enough_information",
        f"The claim references {part}, but the offline fallback cannot verify visible damage without a calibrated observation.",
        ids if ids else "none",
        False,
        "unknown",
    )


def predict_row(row: Mapping[str, str], history: Mapping[str, Mapping[str, str]]) -> Dict[str, str]:
    key = image_case_key(row.get("image_paths", ""))
    observation = VISUAL_OBSERVATIONS.get(key) or fallback_observation(row)
    history_row = history.get(row.get("user_id", ""))
    risk_flags = merge_risk_flags(observation.risk_flags, history_row)

    justification = observation.claim_status_justification
    if history_row and "user_history_risk" in split_flags(history_row.get("history_flags", "none")):
        if "User history" not in justification and "user history" not in justification:
            justification = f"{justification} User history also requires review."

    return {
        "user_id": row.get("user_id", ""),
        "image_paths": row.get("image_paths", ""),
        "user_claim": row.get("user_claim", ""),
        "claim_object": row.get("claim_object", ""),
        "evidence_standard_met": str(observation.evidence_standard_met).lower(),
        "evidence_standard_met_reason": observation.evidence_standard_met_reason,
        "risk_flags": risk_flags,
        "issue_type": observation.issue_type,
        "object_part": observation.object_part,
        "claim_status": observation.claim_status,
        "claim_status_justification": justification,
        "supporting_image_ids": observation.supporting_image_ids,
        "valid_image": str(observation.valid_image).lower(),
        "severity": observation.severity,
    }


def predict_file(input_csv: Path, output_csv: Path, dataset_root: Path) -> List[Dict[str, str]]:
    history = load_user_history(dataset_root)
    rows = load_csv(input_csv)
    predictions = [predict_row(row, history) for row in rows]
    output_csv.parent.mkdir(parents=True, exist_ok=True)
    with output_csv.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=OUTPUT_COLUMNS, quoting=csv.QUOTE_MINIMAL)
        writer.writeheader()
        writer.writerows(predictions)
    return predictions


def default_paths() -> tuple[Path, Path, Path]:
    here = Path(__file__).resolve().parent
    if here.name == "code":
        repo_root = here.parent
    elif (Path.cwd() / "dataset" / "claims.csv").exists():
        repo_root = Path.cwd()
    else:
        repo_root = here
    return repo_root / "dataset" / "claims.csv", repo_root / "output.csv", repo_root / "dataset"


def main() -> None:
    default_input, default_output, default_dataset = default_paths()
    parser = argparse.ArgumentParser(description="Generate evidence-review predictions.")
    parser.add_argument("--input", type=Path, default=default_input)
    parser.add_argument("--output", type=Path, default=default_output)
    parser.add_argument("--dataset-root", type=Path, default=default_dataset)
    args = parser.parse_args()

    predictions = predict_file(args.input, args.output, args.dataset_root)
    print(f"Wrote {len(predictions)} rows to {args.output}")


if __name__ == "__main__":
    main()
